/* TestCallbackFirst has been autogenerated by py-apx generator 0.3.3 */

//////////////////////////////////////////////////////////////////////////////
// INCLUDES
//////////////////////////////////////////////////////////////////////////////
#include <string.h>
#include <stdio.h>
#include "ApxNode_TestCallbackFirst.h"
#include "ApxNode_TestCallbackFirst_Cbk.h"
#include "pack.h"

//////////////////////////////////////////////////////////////////////////////
// CONSTANTS AND DATA TYPES
//////////////////////////////////////////////////////////////////////////////
#define APX_DEFINITON_LEN 73u
#define APX_IN_PORT_DATA_LEN 5u
#define APX_OUT_PORT_DATA_LEN 0u

#define APX_RX_LEN_RU8PORT 1u
#define APX_RX_LEN_RS32PORT 4u

#define APX_RX_OFFSET_RS32PORT 0u
#define APX_RX_OFFSET_RU8PORT 4u

//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
// LOCAL VARIABLES
//////////////////////////////////////////////////////////////////////////////
static const uint8_t m_inPortInitData[APX_IN_PORT_DATA_LEN]= {
   0, 0, 0, 128, 255
};

static uint8 m_inPortdata[APX_IN_PORT_DATA_LEN];
static uint8_t m_inPortDirtyFlags[APX_IN_PORT_DATA_LEN];
static apx_nodeData_t m_nodeData;
static const char *m_apxDefinitionData=
"APX/1.2\n"
"N\"TestCallbackFirst\"\n"
"R\"RS32Port\"l:=-2147483648\n"
"R\"RU8Port\"C:=255\n"
"\n";

//////////////////////////////////////////////////////////////////////////////
// GLOBAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
void ApxNode_Init_TestCallbackFirst(void)
{
   memcpy(&m_inPortdata[0], &m_inPortInitData[0], APX_IN_PORT_DATA_LEN);
   memset(&m_inPortDirtyFlags[0], 0, sizeof(m_inPortDirtyFlags));
   apx_nodeData_create(&m_nodeData, "TestCallbackFirst", (uint8_t*) &m_apxDefinitionData[0], APX_DEFINITON_LEN, &m_inPortdata[0], &m_inPortDirtyFlags[0], APX_IN_PORT_DATA_LEN, 0, 0, 0);
#ifdef APX_POLLED_DATA_MODE
   rbfs_create(&m_outPortDataCmdQueue, &m_outPortDataCmdBuf[0], APX_NUM_OUT_PORTS, APX_DATA_WRITE_CMD_SIZE);
#endif
}

apx_nodeData_t * ApxNode_GetNodeData_TestCallbackFirst(void)
{
   return &m_nodeData;
}

Std_ReturnType ApxNode_Read_TestCallbackFirst_RS32Port(sint32 *val)
{
   apx_nodeData_lockInPortData(&m_nodeData);
   *val = (sint32) unpackLE(&m_inPortdata[0],(uint8) sizeof(sint32));
   apx_nodeData_unlockInPortData(&m_nodeData);
   return E_OK;
}

Std_ReturnType ApxNode_Read_TestCallbackFirst_RU8Port(uint8 *val)
{
   *val = (uint8) m_inPortdata[4];
   return E_OK;
}

void TestCallbackFirst_inPortDataWritten(void *arg, apx_nodeData_t *nodeData, uint32_t offset, uint32_t len)
{
   union data_tag
   {
      sint32 RS32Port;
   } data;
   uint32_t endOffset = offset + len;

   (void)arg;
   (void)nodeData;

   while (offset < endOffset)
   {
      switch(offset)
      {
      case APX_RX_OFFSET_RS32PORT:
         (void) ApxNode_Read_TestCallbackFirst_RS32Port(&data.RS32Port);
         RS32Port_cb_func(data.RS32Port);
         offset += APX_RX_LEN_RS32PORT;
         break;
      //case APX_RX_OFFSET_RU8PORT:
      default:
         offset = endOffset;
      }
   }
}
//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
