/* TestSimpleOnlyR has been autogenerated by py-apx generator 0.4.0 */

//////////////////////////////////////////////////////////////////////////////
// INCLUDES
//////////////////////////////////////////////////////////////////////////////
#include <string.h>
#include <stdio.h>
#include "ApxNode_TestSimpleOnlyR.h"
#include "pack.h"

//////////////////////////////////////////////////////////////////////////////
// CONSTANTS AND DATA TYPES
//////////////////////////////////////////////////////////////////////////////
#define APX_DEFINITON_LEN 49u
#define APX_IN_PORT_DATA_LEN 2u
#define APX_OUT_PORT_DATA_LEN 0u

//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
// LOCAL VARIABLES
//////////////////////////////////////////////////////////////////////////////
static const uint8_t m_inPortInitData[APX_IN_PORT_DATA_LEN]= {
   255, 255
};

static uint8_t m_inPortdata[APX_IN_PORT_DATA_LEN];
static uint8_t m_inPortDirtyFlags[APX_IN_PORT_DATA_LEN];
static apx_nodeData_t m_nodeData;
static const char *m_apxDefinitionData=
"APX/1.2\n"
"N\"TestSimpleOnlyR\"\n"
"R\"RU16Port\"S:=0xffFF\n"
"\n";

//////////////////////////////////////////////////////////////////////////////
// GLOBAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
apx_nodeData_t * ApxNode_Init_TestSimpleOnlyR(void)
{
   memcpy(&m_inPortdata[0], &m_inPortInitData[0], APX_IN_PORT_DATA_LEN);
   memset(&m_inPortDirtyFlags[0], 0, sizeof(m_inPortDirtyFlags));
   apx_nodeData_create(&m_nodeData, "TestSimpleOnlyR", (uint8_t*) &m_apxDefinitionData[0], APX_DEFINITON_LEN, &m_inPortdata[0], &m_inPortDirtyFlags[0], APX_IN_PORT_DATA_LEN, 0, 0, 0);
   return &m_nodeData;
}

apx_nodeData_t * ApxNode_GetNodeData_TestSimpleOnlyR(void)
{
   return &m_nodeData;
}

bool ApxNode_IsConnected_TestSimpleOnlyR(void)
{
   return apx_nodeData_isInPortDataOpen(&m_nodeData);
}

Std_ReturnType ApxNode_Read_TestSimpleOnlyR_RU16Port(uint16 *val)
{
   apx_nodeData_lockInPortData(&m_nodeData);
   *val = (uint16_t) unpackLE(&m_inPortdata[0],(uint8_t) sizeof(uint16_t));
   apx_nodeData_unlockInPortData(&m_nodeData);
   return E_OK;
}

void TestSimpleOnlyR_inPortDataWritten(void *arg, apx_nodeData_t *nodeData, uint32_t offset, uint32_t len)
{
   (void)arg;
   (void)nodeData;
   (void)offset;
   (void)len;
}
//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
