/* TestSimple has been autogenerated by py-apx generator 0.3.4 */

//////////////////////////////////////////////////////////////////////////////
// INCLUDES
//////////////////////////////////////////////////////////////////////////////
#include <string.h>
#include <stdio.h>
#include "ApxNode_TestSimple.h"
#include "pack.h"

//////////////////////////////////////////////////////////////////////////////
// CONSTANTS AND DATA TYPES
//////////////////////////////////////////////////////////////////////////////
#define APX_DEFINITON_LEN 107u
#define APX_IN_PORT_DATA_LEN 5u
#define APX_OUT_PORT_DATA_LEN 5u

//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
// LOCAL VARIABLES
//////////////////////////////////////////////////////////////////////////////
static const uint8_t m_outPortInitData[APX_OUT_PORT_DATA_LEN]= {
   255, 255, 255, 255, 255
};

static uint8_t m_outPortdata[APX_OUT_PORT_DATA_LEN];
static uint8_t m_outPortDirtyFlags[APX_OUT_PORT_DATA_LEN];
static const uint8_t m_inPortInitData[APX_IN_PORT_DATA_LEN]= {
   0, 0, 0, 128, 255
};

static uint8_t m_inPortdata[APX_IN_PORT_DATA_LEN];
static uint8_t m_inPortDirtyFlags[APX_IN_PORT_DATA_LEN];
static apx_nodeData_t m_nodeData;
static const char *m_apxDefinitionData=
"APX/1.2\n"
"N\"TestSimple\"\n"
"P\"PS8Port\"c:=-1\n"
"P\"PU32Port\"L:=4294967295\n"
"R\"RS32Port\"l:=-2147483648\n"
"R\"RU8Port\"C:=255\n"
"\n";

//////////////////////////////////////////////////////////////////////////////
// GLOBAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
apx_nodeData_t * ApxNode_Init_TestSimple(void)
{
   memcpy(&m_inPortdata[0], &m_inPortInitData[0], APX_IN_PORT_DATA_LEN);
   memset(&m_inPortDirtyFlags[0], 0, sizeof(m_inPortDirtyFlags));
   memcpy(&m_outPortdata[0], &m_outPortInitData[0], APX_OUT_PORT_DATA_LEN);
   memset(&m_outPortDirtyFlags[0], 0, sizeof(m_outPortDirtyFlags));
   apx_nodeData_create(&m_nodeData, "TestSimple", (uint8_t*) &m_apxDefinitionData[0], APX_DEFINITON_LEN, &m_inPortdata[0], &m_inPortDirtyFlags[0], APX_IN_PORT_DATA_LEN, &m_outPortdata[0], &m_outPortDirtyFlags[0], APX_OUT_PORT_DATA_LEN);
   return &m_nodeData;
}

apx_nodeData_t * ApxNode_GetNodeData_TestSimple(void)
{
   return &m_nodeData;
}

bool ApxNode_IsConnected_TestSimple(void)
{
   return ( apx_nodeData_isInPortDataOpen(&m_nodeData) && apx_nodeData_isOutPortDataOpen(&m_nodeData) );
}

Std_ReturnType ApxNode_Read_TestSimple_RS32Port(sint32 *val)
{
   apx_nodeData_lockInPortData(&m_nodeData);
   *val = (int32_t) unpackLE(&m_inPortdata[0],(uint8_t) sizeof(int32_t));
   apx_nodeData_unlockInPortData(&m_nodeData);
   return E_OK;
}

Std_ReturnType ApxNode_Read_TestSimple_RU8Port(uint8 *val)
{
   *val = (uint8_t) m_inPortdata[4];
   return E_OK;
}

Std_ReturnType ApxNode_Write_TestSimple_PS8Port(sint8 val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   m_outPortdata[0]=(uint8_t) val;
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 0, 1, false);
   return E_OK;
}

Std_ReturnType ApxNode_Write_TestSimple_PU32Port(uint32 val)
{
   apx_nodeData_lockOutPortData(&m_nodeData);
   packLE(&m_outPortdata[1],(uint32_t) val,(uint8_t) sizeof(uint32_t));
   apx_nodeData_outPortDataWriteNotify(&m_nodeData, 1, 4, false);
   return E_OK;
}

void TestSimple_inPortDataWritten(void *arg, apx_nodeData_t *nodeData, uint32_t offset, uint32_t len)
{
   (void)arg;
   (void)nodeData;
   (void)offset;
   (void)len;
}
//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
