/* TestCallbackLast has been autogenerated by py-apx generator 0.4.2 */

//////////////////////////////////////////////////////////////////////////////
// INCLUDES
//////////////////////////////////////////////////////////////////////////////
#include <string.h>
#include <stdio.h>
#include "ApxNode_TestCallbackLast.h"
#include "ApxNode_TestCallbackLast_Cbk.h"
#include "pack.h"

//////////////////////////////////////////////////////////////////////////////
// CONSTANTS AND DATA TYPES
//////////////////////////////////////////////////////////////////////////////
#define APX_DEFINITON_LEN 72u
#define APX_IN_PORT_DATA_LEN 5u
#define APX_OUT_PORT_DATA_LEN 0u

#define APX_RX_LEN_RU8PORT 1u
#define APX_RX_LEN_RS32PORT 4u

#define APX_RX_OFFSET_RS32PORT 0u
#define APX_RX_OFFSET_RU8PORT 4u

//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
// LOCAL VARIABLES
//////////////////////////////////////////////////////////////////////////////
static const uint8_t m_inPortInitData[APX_IN_PORT_DATA_LEN]= {
   0, 0, 0, 128, 255
};

static uint8_t m_inPortdata[APX_IN_PORT_DATA_LEN];
static uint8_t m_inPortSyncedFlags[APX_IN_PORT_DATA_LEN];
static apx_nodeData_t m_nodeData;
static const char *m_apxDefinitionData=
"APX/1.2\n"
"N\"TestCallbackLast\"\n"
"R\"RS32Port\"l:=-2147483648\n"
"R\"RU8Port\"C:=255\n"
"\n";

//////////////////////////////////////////////////////////////////////////////
// GLOBAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
apx_nodeData_t * ApxNode_Init_TestCallbackLast(void)
{
   apx_nodeDataHandlerTable_t nodeDataHandler;
   memcpy(&m_inPortdata[0], &m_inPortInitData[0], APX_IN_PORT_DATA_LEN);
   memset(&m_inPortSyncedFlags[0], 0, sizeof(m_inPortSyncedFlags));
   apx_nodeData_create(&m_nodeData, "TestCallbackLast", (uint8_t*) &m_apxDefinitionData[0], APX_DEFINITON_LEN, &m_inPortdata[0], &m_inPortSyncedFlags[0], APX_IN_PORT_DATA_LEN, 0, 0, 0);
   memset(&nodeDataHandler, 0, sizeof(nodeDataHandler));
   nodeDataHandler.inPortDataWritten = TestCallbackLast_inPortDataWritten;
   apx_nodeData_setHandlerTable(&m_nodeData, &nodeDataHandler);
   return &m_nodeData;
}

apx_nodeData_t * ApxNode_GetNodeData_TestCallbackLast(void)
{
   return &m_nodeData;
}

bool ApxNode_IsConnected_TestCallbackLast(void)
{
   return apx_nodeData_isInPortDataOpen(&m_nodeData);
}

Std_ReturnType ApxNode_Read_TestCallbackLast_RS32Port(sint32 *val)
{
   apx_nodeData_lockInPortData(&m_nodeData);
   *val = (int32_t) unpackLE(&m_inPortdata[0],(uint8_t) sizeof(int32_t));
   apx_nodeData_unlockInPortData(&m_nodeData);
   return E_OK;
}

Std_ReturnType ApxNode_Read_TestCallbackLast_RU8Port(uint8 *val)
{
   *val = (uint8_t) m_inPortdata[4];
   return E_OK;
}

void TestCallbackLast_inPortDataWritten(void *arg, apx_nodeData_t *nodeData, uint32_t offset, uint32_t len)
{
   union data_tag
   {
      uint8 RU8Port;
   } data;
   uint32_t endOffset = offset + len;

   (void)arg;
   (void)nodeData;

   if (offset < APX_RX_OFFSET_RU8PORT)
   {
      offset = APX_RX_OFFSET_RU8PORT;
   }
   while (offset < endOffset)
   {
      switch(offset)
      {
      case APX_RX_OFFSET_RU8PORT:
         (void) ApxNode_Read_TestCallbackLast_RU8Port(&data.RU8Port);
         RU8Port_cb_func(data.RU8Port);
         offset += APX_RX_LEN_RU8PORT;
         break;
      default:
         offset = endOffset;
      }
   }
}
//////////////////////////////////////////////////////////////////////////////
// LOCAL FUNCTIONS
//////////////////////////////////////////////////////////////////////////////
