class ParseError(RuntimeError):
   pass

class ValueTypeError(ValueError):
   pass

class ValueRangeError(ValueError):
   pass

TYPE_CODE_NONE = 0
TYPE_CODE_UINT8 = 1
TYPE_CODE_UINT16 = 2
TYPE_CODE_UINT32 = 3
TYPE_CODE_UINT64 = 4
TYPE_CODE_INT8 = 5
TYPE_CODE_INT16 = 6
TYPE_CODE_INT32 = 7
TYPE_CODE_INT64 = 8
TYPE_CODE_CHAR = 9
TYPE_CODE_CHAR8 = 10
TYPE_CODE_CHAR16 = 11 #RESERVED FOR APX IDL v1.4
TYPE_CODE_CHAR32 = 12 #RESERVED FOR APX IDL v1.4
TYPE_CODE_BOOL = 13
TYPE_CODE_BYTE = 14
TYPE_CODE_RECORD = 15
TYPE_CODE_REF_ID = 16
TYPE_CODE_REF_NAME = 17
TYPE_CODE_REF_PTR = 18

TOKEN_CLASS_NONE = 0
TOKEN_CLASS_DATA_ELEMENT = 1
TOKEN_GROUP_DECLARATION = 2 #RESERVED FOR APX IDL v1.4
TOKEN_FUNCTION_DECLARATION = 3 #RESERVED FOR APX IDL v1.4
